"""DocumentSpec composition layer."""

from __future__ import annotations

import pytest

from hyperweave.compose.document import DocumentSpec, render
from hyperweave.compose.document.models import (
    ArtifactBlock,
    CaptionBlock,
    FlowBlock,
    HeadingBlock,
    ProseBlock,
)
from hyperweave.core.models import ComposeSpec
from hyperweave.verbs import extract, verify

_MATRIX = {
    "title": "Cost",
    "columns": [{"id": "m", "label": "MODEL"}, {"id": "c", "label": "COST", "kind": "numeric"}],
    "rows": [{"label": "Qwen", "cells": [{"value": "Qwen"}, {"value": "0.12"}]}],
}
_DIAGRAM = {
    "topology": "pipeline",
    "nodes": [{"id": "a", "label": "A"}, {"id": "b", "label": "B"}, {"id": "c", "label": "C"}],
}


def _doc() -> DocumentSpec:
    return DocumentSpec(
        title="Model Cost Report",
        intent="compare model cost and show the pipeline",
        genome="primer",
        variant="porcelain",
        blocks=[
            HeadingBlock(text="Cost by model", level=1),
            ProseBlock(text="The cheapest model wins on price; the pipeline below shows where it sits."),
            ArtifactBlock(frame=ComposeSpec(type="matrix", matrix=_MATRIX), caption="Figure 1"),
            FlowBlock(diagram=_DIAGRAM, caption="Figure 2"),
            CaptionBlock(text="Generated by the document agent."),
        ],
    )


def test_render_svg_stacks_blocks_and_embeds_payload() -> None:
    r = render(_doc(), "svg")
    assert r.width > 0 and r.height > 0
    assert r.svg.count("data-hw-block=") == 2  # matrix + flow embedded
    assert 'schema="document/1"' in r.svg
    assert "agents:" in r.svg  # self-instruction comment


def test_render_markdown_is_a_text_shadow() -> None:
    md = render(_doc(), "markdown").markdown
    assert md.startswith("# Model Cost Report")
    assert "MODEL" in md  # the matrix table shadow is inlined


def test_render_json_is_payload_plus_envelope() -> None:
    r = render(_doc(), "json")
    assert r.payload is not None and len(r.payload["blocks"]) == 5
    assert r.envelope is not None and r.envelope["k"] == "visual-doc"


def test_html_target_is_a_reserved_seam() -> None:
    with pytest.raises(NotImplementedError):
        render(_doc(), "html")


def test_document_is_the_payload_verbs_generalize() -> None:
    svg = render(_doc(), "svg").svg
    # DocumentSpec IS the payload — extract reads it, verify confirms the doc is its data
    assert extract(svg, respond="payload").schema == "document/1"
    assert verify(svg).hash_valid


def test_embedded_mode_drops_the_background() -> None:
    standalone = render(_doc().model_copy(update={"mode": "standalone"}), "svg").svg
    embedded = render(_doc().model_copy(update={"mode": "embedded"}), "svg").svg
    assert "var(--dna-surface" in standalone
    assert 'data-hw-mode="embedded"' in embedded


def test_durable_disk_tier_survives_memory_eviction(tmp_path: object) -> None:
    # The reviewer's pin: /v1/a/{id} must resolve cross-session for documents.
    from hyperweave.compose import artifact_store

    try:
        artifact_store.configure_disk_cache(tmp_path)
        artifact_store.store_artifact("sha256:deadbeef", "<svg>doc</svg>")
        artifact_store.reset_cache()  # simulate process restart / eviction
        assert artifact_store.get_artifact("deadbeef") == "<svg>doc</svg>"  # served from disk
    finally:
        artifact_store.configure_disk_cache(None)
        artifact_store.reset_cache()


def test_distinct_block_ids_no_collision() -> None:
    # two identical matrix artifacts must namespace their ids (no duplicate gradient id)
    doc = DocumentSpec(
        title="Twins",
        genome="primer",
        blocks=[
            ArtifactBlock(frame=ComposeSpec(type="matrix", matrix=_MATRIX)),
            ArtifactBlock(frame=ComposeSpec(type="matrix", matrix=_MATRIX)),
        ],
    )
    svg = render(doc, "svg").svg
    import re

    ids = re.findall(r'\bid="([^"]+)"', svg)
    assert len(ids) == len(set(ids)), "embedded block ids must be unique (namespaced per block)"
